# Generated by Django 4.1 on 2022-10-25 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band_role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBandRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('band_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_role_id_user', to='band_role.bandrole')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_band_role_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
