# Generated by Django 4.1 on 2022-10-28 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band_role', '0003_alter_userbandrole_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbandrole',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_band_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
