# Generated by Django 4.1 on 2022-10-26 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band_role', '0002_userbandrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamBandRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('band_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_role_jam', to='band_role.bandrole')),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jam_band_role', to='jams.jam')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer_band_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
