# Generated by Django 4.1 on 2022-10-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0002_jambandrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='jam',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
