# Generated by Django 4.1 on 2022-10-26 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jams', '0003_jam_start_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jam_invitation', to='jams.jam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitation_jam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
